# Generated by Django 4.2.4 on 2023-08-31 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
